export const motivationalPhrases = [
    "Every word you learn is a step toward fluency! 🌟",
    "You're building bridges between cultures! 🌉",
    "Small steps lead to big achievements in language learning! 🚀",
    "Your dedication to French is inspiring! ✨",
    "Keep going! Future you will be thankful! 💪",
    "You're making progress, even if you don't see it! 🌱",
    "Learning a language is a journey, enjoy the ride! 🚗",
    "Your brain is growing with every French word! 🧠",
    "Consistency is the key to mastery! 🔑",
    "You're becoming more international every day! 🌍",
    "Every mistake is a learning opportunity! 📚",
    "Your future self will thank you for learning French! 🙏",
    "You're developing a superpower - bilingualism! ⚡",
    "Knowledge of languages is the doorway to wisdom! 🚪",
    "You're creating new neural pathways! 🔄",
    "Language learning is self-improvement in disguise! 🎭",
    "Each session makes you stronger! 💪",
    "You're expanding your world view! 🌎",
    "Learning French is an investment in yourself! 📈",
    "Keep pushing - you're doing great! 🌟",
    "Your persistence is admirable! 🏆",
    "You're building valuable skills! 🛠️",
    "Every session counts toward your goals! 🎯",
    "You're becoming more versatile! 🔄",
    "Language learning is mind expansion! 🧠",
    "Your efforts will pay off! 💫",
    "You're on the path to success! 🛤️",
    "Learning French opens new doors! 🚪",
    "You're growing stronger every day! 🌱",
    "Keep that momentum going! 🔄",
    "Your dedication is inspiring! ✨",
    "You're making incredible progress! 📈",
    "Every word learned is a victory! 🏆",
    "You're becoming more cultured! 🎭",
    "Learning French is a gift to yourself! 🎁",
    "Your journey is unique and valuable! 🌟",
    "You're building a better future! 🌅",
    "Knowledge is power, keep learning! 💪",
    "You're expanding your horizons! 🌅",
    "Each session makes a difference! ✨",
    "You're becoming more sophisticated! 🎩",
    "Learning is a form of self-respect! 💝",
    "You're investing in your mind! 🧠",
    "Keep that learning spirit alive! 🔥",
    "You're doing something amazing! 🌟",
    "Your efforts are paying off! 💫",
    "You're becoming more worldly! 🌍",
    "Learning French is transforming you! 🦋",
    "You're creating new opportunities! 🚪",
    "Keep challenging yourself! 💪",
    "You're making yourself proud! 🏆",
    "Every session is progress! 📈",
    "You're building valuable skills! 🛠️",
    "Learning French is self-care! 💝",
    "You're becoming more versatile! 🔄",
    "Keep that curiosity alive! 🔍",
    "You're on a path to excellence! ⭐",
    "Your commitment is admirable! 👏",
    "Learning is a journey, enjoy it! 🚗",
    "You're becoming more capable! 💪",
    "Every effort counts! ✨",
    "You're building something special! 🏗️",
    "Keep that momentum strong! 🔄",
    "You're making great strides! 👣",
    "Learning French is an adventure! 🗺️",
    "You're growing every day! 🌱",
    "Your progress is inspiring! ✨",
    "Keep pushing forward! 🚀",
    "You're becoming bilingual! 🗣️",
    "Every word counts! 📚",
    "You're creating new connections! 🤝",
    "Learning is a superpower! ⚡",
    "You're becoming more educated! 🎓",
    "Keep that focus strong! 🎯",
    "You're making it happen! ✨",
    "Learning French is freedom! 🕊️",
    "You're expanding your mind! 🧠",
    "Every lesson matters! 📖",
    "You're building confidence! 💪",
    "Keep that spirit high! 🌟",
    "You're becoming more global! 🌍",
    "Learning is living! 💫",
    "You're creating possibilities! ✨",
    "Keep believing in yourself! 💝",
    "You're making magic happen! ✨",
    "Learning French is growth! 🌱",
    "You're becoming stronger! 💪",
    "Every day is progress! 📈",
    "You're building your future! 🏗️",
    "Keep that determination! 🔥",
    "You're making history! 📚",
    "Learning is power! ⚡",
    "You're becoming exceptional! 🌟",
    "Keep shining bright! ✨",
    "You're making waves! 🌊",
    "Learning French is wisdom! 🦉",
    "You're becoming amazing! 🌟",
    "Every moment counts! ⏱️",
    "You're building dreams! 🌈",
    "Keep that passion alive! 💫",
    "You're making progress! 📈",
    "Learning is living fully! 🌟",
    "You're becoming unstoppable! 🚀",
    "Keep reaching higher! 🌟",
    "You're making it count! ✨"
  ];